### ISSUE TITLE
Train AutoEncoderKL/VQGAN

### ISSUE THREAD

**Issue by CrashBomb** [buxiangzhiren/Asymmetric_VQGAN#11]
Hello,

Thank you for open sourcing your work ! I have a question about training a new autoencoder model. I base my configuration file on autoencoder_kl_32x32x4_train.yaml and modify it to my dataset.
But if I understand well, with this configuration file, I train an AutoEncoderKL, not a VQGAN. I checked all the others configuration files for the autoencoder part and they all use AutoEncoderKL as model target. 
When does the VQGAN aspect is used ? 
 
Maybe I didn't understand well all the process, sorry in advance in this case.
Thank you !

**Comment by buxiangzhiren** [comment]
we did not release the code about the version of VQGAN. But you can copy the codes of the decoder in the KL and replace the decoder in the VQGAN with what you copied.

**Comment by CrashBomb** [comment]
Okay, thank you for the answer !

Have a nice day !
