### ISSUE TITLE
applicable on SD-2

### ISSUE THREAD

**Issue by Tsingularity** [buxiangzhiren/Asymmetric_VQGAN#2]
Hi, thanks for the great work and sharing the ckpt!

I noticed that, you mentioned this model is trained using sdv1-5, just wondering is it directly applicable to the inpainting model of SD2, i.e., directly replace the sd2 inpaint model's decoder with your provided ckpt?

Thanks!

**Comment by buxiangzhiren** [comment]
Due to the different parameters of the VQGAN in sdv1-5 and sdv2, the ckpt provided by us cannot be directly applicable to the inpainting model of sdv2.

**Comment by Tsingularity** [comment]
thanks for the quick reply! and do please let me know if you release the sd2 compatible ckpt in the future. It would be a great add-on to the whole community!
