### ISSUE TITLE
some errors in inference

### ISSUE THREAD

**Issue by kelisiya** [buxiangzhiren/Asymmetric_VQGAN#3]
when I use code to inference , 
`No such file or directory stable_diff_vqauto_text.ckpt` , how to find this ckpt ?

**Comment by buxiangzhiren** [comment]
We are sorry for this error, you just need to replace this directory (stable_diff_vqauto_text.ckpt) with our pre-trained checkpoint.

**Comment by buxiangzhiren** [comment]
> We are sorry for this error, you just need to replace this directory (stable_diff_vqauto_text.ckpt) with our pre-trained checkpoint.

or you can remove this line "ckpt:xxx" in config.yaml

**Comment by kelisiya** [comment]
> We are sorry for this error, you just need to replace this directory (stable_diff_vqauto_text.ckpt) with our pre-trained checkpoint.

thanks for your reply ,and now the code has other error for inference : `AttributeError: 'AutoencoderKL' object has no attribute 'num_timesteps/cond_stage_model'` , I found these para in DDPM not DDIM .

**Comment by buxiangzhiren** [comment]
Can you show me the whole logs of this error?

**Comment by kelisiya** [comment]
> Can you show me the whole logs of this error?

`CUDA_VISIBLE_DEVICES=1  python inpaint_st.py  
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 768 in_channels
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
Restored from ./output/pre_models/larger1.5.ckpt with 0 missing and 0 unexpected keys
0it [00:00, ?it/s]loaded input image of size (512, 512)
resized to (512, 512)
Loading model from ./output/pre_models/larger1.5.ckpt
Global Step: 120030
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 768 in_channels
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
Restored from ./output/pre_models/larger1.5.ckpt with 0 missing and 0 unexpected keys
0it [00:04, ?it/s]
Traceback (most recent call last):
  File "inpaint_st.py", line 250, in <module>
    run(opt)
  File "inpaint_st.py", line 191, in run
    result = inpaint(
  File "inpaint_st.py", line 114, in inpaint
    c = model.cond_stage_model.encode(batch["txt"])
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AutoencoderKL' object has no attribute 'cond_stage_model'`

**Comment by kelisiya** [comment]
> Can you show me the whole logs of this error?

I print the config log :
`config load model  {'base_learning_rate': 4.5e-06, 'target': 'ldm.models.autoencoder_large.AutoencoderKL', 'params': {'ckpt_path': './output/pre_models/larger1.5.ckpt', 'embed_dim': 4, 'num_gpus': 8, 'scheduler_config': {'target': 'ldm.lr_scheduler.LambdaWarmUpCosineScheduler', 'params': {'verbosity_interval': 0, 'warm_up_steps': 5000, 'lr_start': 0.01, 'lr_max': 1}}, 'scheduler_config_d': {'target': 'ldm.lr_scheduler.LambdaWarmUpCosineScheduler_D', 'params': {'verbosity_interval': 0, 'warm_up_steps': 5000, 'lr_start': 0.01, 'lr_max': 1}}, 'lossconfig': {'target': 'ldm.modules.losses.LPIPSWithDiscriminator', 'params': {'disc_start': 50001, 'kl_weight': 1e-06, 'disc_weight': 0.8}}, 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}}}`

**Comment by buxiangzhiren** [comment]
what's your config_d

**Comment by buxiangzhiren** [comment]
The model which is used in line 114 (c = model.cond_stage_model.encode(batch["txt"])) should be the diffusion model instead of our VQGAN. I think that you give the wrong directory to config_d.

**Comment by kelisiya** [comment]
> The model which is used in line 114 (c = model.cond_stage_model.encode(batch["txt"])) should be the diffusion model instead of our VQGAN. I think that you give the wrong directory to config_d.

thanks !

**Comment by kelisiya** [comment]
> The model which is used in line 114 (c = model.cond_stage_model.encode(batch["txt"])) should be the diffusion model instead of our VQGAN. I think that you give the wrong directory to config_d.

I saw that the paper uses reference img as a condition, is it supported in the code?

**Comment by buxiangzhiren** [comment]
Did you mean the paint-by-example task?

**Comment by kelisiya** [comment]
> Did you mean the paint-by-example task?

Yes , because I saw a related experiment in the paper, I was curious about this possibility.

**Comment by buxiangzhiren** [comment]
Changing the model.decode_first_stage to our decoder as the same as the inpaint_st.py

**Comment by buxiangzhiren** [comment]
https://github.com/buxiangzhiren/Asymmetric_VQGAN/blob/main/inpaint_st.py#L149

**Comment by kelisiya** [comment]
> https://github.com/buxiangzhiren/Asymmetric_VQGAN/blob/main/inpaint_st.py#L149

very very thanks(
